"""Log LinkedIn message to Jungeun (Christine) Yi - 2026-07-06."""
import json, urllib.request, datetime

ENV = r'C:\Users\reyma\.hermes\.env'
with open(ENV, 'r', encoding='utf-8') as f:
    T = None
    for line in f:
        if line.lstrip().startswith('HUBSPOT_ACCESS_TOKEN='):
            T = line.split('=', 1)[1].strip().strip('"').strip("'")
            break

BASE = 'https://api.hubapi.com'

def http(method, url, body=None):
    req = urllib.request.Request(url, method=method)
    req.add_header('Authorization', f'Bearer {T}')
    req.add_header('Content-Type', 'application/json')
    data = json.dumps(body).encode() if body is not None else None
    try:
        with urllib.request.urlopen(req, data=data, timeout=15) as resp:
            return resp.status, (json.loads(resp.read().decode()) if resp.length else {})
    except urllib.error.HTTPError as e:
        try:
            return e.code, json.loads(e.read().decode())
        except Exception:
            return e.code, e.read().decode()[:300]

now_iso = datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%S.000Z')
today = datetime.date.today().isoformat()

# Jungeun Yi HubSpot ID = 512570728144 (verified earlier this session)
contact_id = '512570728144'

# Update lead status: NEW -> OPEN
sc, d = http('PATCH', f'{BASE}/crm/v3/objects/contacts/{contact_id}', {
    'properties': {
        'hs_lead_status': 'OPEN'
    }
})
print(f'PATCH Jungeun Yi status=OPEN: HTTP {sc}')

# Engagement note
note_body = (
    f'**LINKEDIN MESSAGE SENT - 2026-07-06 ~16:05 PHT**\n\n'
    f'Channel: LinkedIn direct message\n'
    f'Profile: https://www.linkedin.com/in/jungeun-christine-yi-58b1a224\n'
    f'Message length: 1,392 chars (202 words, within LinkedIn 1900 char InMail limit)\n\n'
    f'KEY ANGLES USED:\n'
    f'- Referenced her 10+ years experience in raw materials procurement + transportation at POSCO Steel\n'
    f'- Referenced NPSI (Nickel Premium Solutions) JV with MC Group\n'
    f'- Connected to POSCO Future M HPAL/MHP battery supply chain\n'
    f'- Referenced her deep expertise in shipping contracts, supply chain, inventory management\n'
    f'- Cross-referenced email sent to jungeun.yi@posco.com (CC young-hoon.you@posco.com)\n'
    f'- Referenced parallel LinkedIn outreach to Young-Hoon YOU (Note 381270329046)\n'
    f'- Asked for brief conversation, no hard sell\n\n'
    f'FOLLOW-UP PLAN: +7 days (around 2026-07-13). If no response, follow up via email again '
    f'to jungeun.yi@posco.com. Use task 381110568668 + create a parallel task for Yi.\n\n'
    f'NOTE: User opted to send the message manually via copy-paste (browser session was not '
    f'authenticated to LinkedIn). Message text was generated by agent and pasted by user.\n\n'
    f'Source: ECONARES sales outreach 2026-07-06.'
)
sc, d = http('POST', f'{BASE}/crm/v3/objects/notes', {
    'properties': {'hs_timestamp': now_iso, 'hs_note_body': note_body},
    'associations': [{'to': {'id': contact_id}, 'types': [{'associationCategory': 'HUBSPOT_DEFINED', 'associationTypeId': 202}]}]
})
note_id = d.get('id', '?') if isinstance(d, dict) else '?'
print(f'NOTE LinkedIn outreach logged: HTTP {sc} | id={note_id}')

# Follow-up task
followup_due = (datetime.date.today() + datetime.timedelta(days=7)).isoformat() + 'T09:00:00.000Z'
task_body = {
    'properties': {
        'hs_task_subject': 'Follow-up: Jungeun Yi (POSCO) - LinkedIn message sent 2026-07-06',
        'hs_task_body': 'If no response to LinkedIn message sent 2026-07-06, follow up via email to jungeun.yi@posco.com (CC young-hoon.you@posco.com). Reference the LinkedIn outreach in note. Parallel task to Young-Hoon YOU follow-up (Task 381110568668) - both due same day.',
        'hs_task_status': 'NOT_STARTED',
        'hs_task_priority': 'MEDIUM',
        'hs_timestamp': followup_due
    },
    'associations': [{'to': {'id': contact_id}, 'types': [{'associationCategory': 'HUBSPOT_DEFINED', 'associationTypeId': 204}]}]
}
sc, d = http('POST', f'{BASE}/crm/v3/objects/tasks', task_body)
task_id = d.get('id', '?') if isinstance(d, dict) else '?'
print(f'TASK follow-up created: HTTP {sc} | id={task_id} | due {followup_due}')

print()
print('=== Done ===')
print(f'Contact: Jungeun Yi ({contact_id})')
print(f'Note: {note_id}')
print(f'Task: {task_id} (due {followup_due})')