"""Log LinkedIn message sent to Young-Hoon YOU on 2026-07-06."""
import json, urllib.request, datetime

ENV = r'C:\Users\reyma\.hermes\.env'
with open(ENV, 'r', encoding='utf-8') as f:
    T = None
    for line in f:
        if line.lstrip().startswith('HUBSPOT_ACCESS_TOKEN='):
            T = line.split('=', 1)[1].strip().strip('"').strip("'")
            break

BASE = 'https://api.hubapi.com'

def http(method, url, body=None):
    req = urllib.request.Request(url, method=method)
    req.add_header('Authorization', f'Bearer {T}')
    req.add_header('Content-Type', 'application/json')
    data = json.dumps(body).encode() if body is not None else None
    try:
        with urllib.request.urlopen(req, data=data, timeout=15) as resp:
            return resp.status, (json.loads(resp.read().decode()) if resp.length else {})
    except urllib.error.HTTPError as e:
        try:
            return e.code, json.loads(e.read().decode())
        except Exception:
            return e.code, e.read().decode()[:300]

now_iso = datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%S.000Z')
today = datetime.date.today().isoformat()

# Young-Hoon YOU HubSpot ID = 514282132201 (verified earlier this session)
contact_id = '514282132201'

# Increment the LinkedIn outreach engagement count on the contact
sc, d = http('PATCH', f'{BASE}/crm/v3/objects/contacts/{contact_id}', {
    'properties': {
        'hs_lead_status': 'OPEN'  # was NEW; now OPEN because outreach is in flight
    }
})
print(f'PATCH Young-Hoon YOU status=OPEN: HTTP {sc}')

# Add engagement note
note_body = (
    f'**LINKEDIN MESSAGE SENT - 2026-07-06 ~15:40 PHT**\n\n'
    f'Channel: LinkedIn direct message\n'
    f'Profile: https://www.linkedin.com/in/young-hoon-you-9a1863140\n'
    f'Message length: 1,273 chars (184 words, within LinkedIn 1900 char InMail limit)\n\n'
    f'KEY ANGLES USED:\n'
    f'- Referenced NPSI (Nickel Premium Solutions) JV with MC Group\n'
    f'- Referenced his SMSP/POSCO JV board membership\n'
    f'- Connected to POSCO Future M HPAL/MHP battery supply chain\n'
    f'- Referenced his 10+ years procurement of Ni Cathodes/Briquette/Ferro-Ni\n'
    f'- Cross-referenced the email also sent to young-hoon.you@posco.com (CC jungeun.yi@posco.com)\n'
    f'- Asked for brief conversation, no hard sell\n\n'
    f'FOLLOW-UP PLAN: +7 days (around 2026-07-13). If no response, follow up via email again '
    f'to both young-hoon.you@posco.com and jungeun.yi@posco.com.\n\n'
    f'NOTE: User opted to send the message manually via copy-paste (browser session was not '
    f'authenticated to LinkedIn). Message text was generated by agent and pasted by user.\n\n'
    f'Source: ECONARES sales outreach 2026-07-06.'
)
sc, d = http('POST', f'{BASE}/crm/v3/objects/notes', {
    'properties': {'hs_timestamp': now_iso, 'hs_note_body': note_body},
    'associations': [{'to': {'id': contact_id}, 'types': [{'associationCategory': 'HUBSPOT_DEFINED', 'associationTypeId': 202}]}]
})
note_id = d.get('id', '?') if isinstance(d, dict) else '?'
print(f'NOTE LinkedIn outreach logged: HTTP {sc} | id={note_id}')

# Also log a task for the +7 day follow-up
# Task due 2026-07-13
followup_due = (datetime.date.today() + datetime.timedelta(days=7)).isoformat() + 'T09:00:00.000Z'
task_body = {
    'properties': {
        'hs_task_subject': 'Follow-up: Young-Hoon YOU (POSCO) — LinkedIn message sent 2026-07-06',
        'hs_task_body': 'If no response to LinkedIn message sent 2026-07-06, follow up via email to young-hoon.you@posco.com (CC jungeun.yi@posco.com). Reference the LinkedIn outreach in note 514282132201.',
        'hs_task_status': 'NOT_STARTED',
        'hs_task_priority': 'MEDIUM',
        'hs_timestamp': followup_due
    },
    'associations': [{'to': {'id': contact_id}, 'types': [{'associationCategory': 'HUBSPOT_DEFINED', 'associationTypeId': 204}]}]
}
sc, d = http('POST', f'{BASE}/crm/v3/objects/tasks', task_body)
task_id = d.get('id', '?') if isinstance(d, dict) else '?'
print(f'TASK follow-up created: HTTP {sc} | id={task_id} | due {followup_due}')

# Also bump POSCO Holdings company record
sc, d = http('PATCH', f'{BASE}/crm/v3/objects/companies/331643911869', {
    'properties': {
        'description': (
            'POSCO Holdings, Inc. (포스코홀딩스, KRX 005490) - Korean steel and EV battery materials holding company. '
            'World 5th largest steelmaker (~17.2 MT/yr); parent of POSCO International, POSCO Future M (battery cathode), '
            'POSCO-HY Clean Metal, POSCO Lithium Solution, POSCO Silicon Solution. '
            '**POSCO Future M JV with MC Group (NPSI - Nickel Premium Solutions Inc.) plans to acquire ~200M tons of '
            'Philippine nickel ore by 2026** — major PH nickel ore demand signal. '
            'Raw materials procurement is centralized; materials@posco.com is the official raw-materials line. '
            'Phone +82 2-3457-0114. HQ Incheon, South Korea. 1,231 employees (+2.3% YoY). KRW 69.1T revenue.'
        )
    }
})
print(f'PATCH POSCO Holdings company: HTTP {sc}')

print()
print('=== Done ===')
print(f'Contact: Young-Hoon YOU ({contact_id})')
print(f'Note: {note_id}')
print(f'Task: {task_id} (due {followup_due})')